# Generated by Django 4.2 on 2025-11-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AptCost",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("apt_name", models.CharField(max_length=30)),
                ("build_year", models.CharField(max_length=5)),
                ("deal_amount", models.CharField(max_length=20)),
                ("deal_day", models.CharField(max_length=5)),
                ("deal_month", models.CharField(max_length=5)),
                ("deal_year", models.CharField(max_length=5)),
                ("exclu_usearea", models.CharField(max_length=20)),
                ("floor", models.CharField(max_length=5)),
                ("land_leaseholdgbn", models.CharField(max_length=5)),
                ("sgg_cd", models.CharField(max_length=10)),
                ("umd_nm", models.CharField(max_length=30)),
            ],
        ),
    ]
